name: Pull Request Comment Trigger Example
on:
    pull_request:
        braches: [main]
    issue_comment:
        types: [created]

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: mokeseven7/pull-request@main
              id: check
              with:
                  trigger: "#deploy"
                  reaction: rocket
            - run: "echo Found it!"
              if: steps.check.outputs.triggered == 'true'
